config/routes.rb
Rails.application.routes.draw do

  # => auto generated routes, not really usefull for the purpose of the challenge
  #  resources :offers
  #  resources :companies

  get 'companies' => 'companies#index'
  get 'companies/:id' => 'companies#show'
  get 'offers' => 'offers#index'
  get 'offers/:id' => 'offers#show'
  get 'search' => 'search#search'
  root 'search#search'
end

app/models/company.rb
class Company < ActiveRecord::Base

  #will paginate per_page conf
  self.per_page = 15

  #relations
  has_many :offers

end

app/models/offer.rb
require 'elasticsearch/model'

class Offer < ActiveRecord::Base
  #Hack to have column named type in offers
  self.inheritance_column = :_type_disabled

  #will paginate per_page conf
  self.per_page = 20

  #relations
  belongs_to :company

  #ElasticSearch integration
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

end

Offer.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.paginate(:page => params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :logo_url, :website_url)
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers  = Offer.paginate(:page => params[:page])
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:city, :company_id, :country_code, :country_name, :currency_code, :expires_at, :nice_to_have, :perks, :published_at, :reward, :remote, :relocation_paid, :role_description, :salary_low, :salary_high, :successful?, :title, :work_from_home, :type, :tags)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  #Search for skills in job offers
  def search
    #Make sure user selected either one button or searched keywords
    if params["/search"].nil?
      @offers = []
      @companies = []

      #If user searched using our buttons
    else
      hits = []
      #iterate to search for each selected skill in job offers
      #.reject! removes the empty field that simple_form sends in params
      params["/search"]["query"].reject!(&:empty?).each do |q|
        #Get the offers for each button and push them in the hits array
        @offers = Offer.search(q).records
        hits.push(*@offers.results)
      end
      #collect all company ids
      company_ids = hits.map { |r| r.company_id }
      #collect respective companies to display
      @companies = Company.where(:id => company_ids)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/search_helper.rb
module SearchHelper

  def companies_count
    return Company.count
  end

  def offers_count
    return Offer.count
  end
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => "form-horizontal company" } do |f| %>

    <% if @company.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@company[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@company[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :logo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :logo_url, :class => 'form-control' %>
    </div>
    <%= error_span(@company[:logo_url]) %>
  </div>
  <div class="control-group">
    <%= f.label :website_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website_url, :class => 'form-control' %>
    </div>
    <%= error_span(@company[:website_url]) %>
  </div>
  <div class="control-group">
    <%= f.label :short_pitch, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :short_pitch, :class => 'form-control' %>
    </div>
    <%= error_span(@company[:short_pitch]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            companies_path, :class => 'btn btn-default' %>

<% end %>

app/views/companies/_index.html.erb
<%- model_class = Company -%>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @companies.each do |c| %>
  <div class="panel panel-exists">
    <div class="panel-heading" role="tab" id="heading<%=c.id%>">
      <table class="table">
        <tr height="120px">
          <td width="20%">
            <%=link_to image_tag(c.logo_url, :border => 0, :alt => 'Logo', :title => '', :height => '120px'), c.website_url, :id => 'invisible_link' %>
          </td>
          <td width="60%">
            <h1 class="">
            <%=c.name %>
            </h1>
            <br>
            <blockquote class="blockquote-reverse">
              <em> <%= c.short_pitch %> </em>
            </blockquote>
          </td>
          <td width="20%" class="text-right">
            <a style ="display:<%= c.description.nil? ? 'none' : '' %>;" id ="invisible_link" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=c.id%>" aria-expanded="false" aria-controls="collapse<%=c.id%>">
              <%=fa_icon "caret-square-o-down 5x", class: "fa-mod"  %>
            </a>
          </td>
        </tr>
      </table>
    </div>
    <div id="collapse<%=c.id%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=c.id%>">
      <div class="panel-body">
        <table class="table">
          <thead>
            <tr>
              <th><%= model_class.human_attribute_name(:description) %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= c.description %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="main-row">
  <%= will_paginate @companies, renderer: BootstrapPagination::Rails %>
    <%= render "index"  %>
  </div>
</div>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @company.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:logo_url) %>:</strong></dt>
  <dd><%= @company.logo_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website_url) %>:</strong></dt>
  <dd><%= @company.website_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_pitch) %>:</strong></dt>
  <dd><%= @company.short_pitch %></dd>
</dl>

app/views/layouts/_navbar.html.erb
<div class ="row">
  <header id="header" class="">
    <nav class="navbar navbar-fixed-top " style="background-color:white;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <ul class="nav navbar-nav ">
            <li> <a href="<%= root_path%>"><h3>Findr.co</h3></a></li>
          </ul>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%=companies_path  %>"><h3>Companies</h3></a></li>
            <li><a href="<%=search_path%>"><h3>Search</h3></a></li>
            <li><a href="http://jpserra.github.io"><h3>Contact</h3></a></li>
            <li>
              <!--
              <%= form_for search_path, method: :get, class: "form-inline" do |f|%>
              <div class="form-group" width="100px">
                <div width="50%">
                  <%= text_field_tag :q, params[:q], class: "form-control" %>
                </div>
                <div width= "50%">
                  <%= submit_tag "Go", name: nil , class: "btn btn-large btn-default btn-lg blank-button " %>
                </div>
              </div>
              -->
            <% end %></li>
          </ul>
          </div><!--/.nav-collapse -->
        </div>
        <hr style="margin:0px;">
      </nav>
      </header><!-- /header -->
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobboxChallenge</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_for @offer, :html => { :class => "form-horizontal offer" } do |f| %>
<% if @offer.errors.any? %>
<div id="error_expl" class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @offer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<div class="control-group">
  <%= f.label :city, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :city, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:city]) %>
</div>
<div class="control-group">
  <%= f.label :company_id, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :company_id, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:company_id]) %>
</div>
<div class="control-group">
  <%= f.label :country_code, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :country_code, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:country_code]) %>
</div>
<div class="control-group">
  <%= f.label :country_name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :country_name, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:country_name]) %>
</div>
<div class="control-group">
  <%= f.label :currency_code, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :currency_code, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:currency_code]) %>
</div>
<div class="control-group">
  <%= f.label :expires_at, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :expires_at, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:expires_at]) %>
</div>
<div class="control-group">
  <%= f.label :nice_to_have, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :nice_to_have, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:nice_to_have]) %>
</div>
<div class="control-group">
  <%= f.label :perks, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :perks, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:perks]) %>
</div>
<div class="control-group">
  <%= f.label :published_at, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :published_at, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:published_at]) %>
</div>
<div class="control-group">
  <%= f.label :reward, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :reward, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:reward]) %>
</div>
<div class="control-group">
  <%= f.label :remote, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :remote, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:remote]) %>
</div>
<div class="control-group">
  <%= f.label :relocation_paid, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :relocation_paid, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:relocation_paid]) %>
</div>
<div class="control-group">
  <%= f.label :role_description, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :role_description, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:role_description]) %>
</div>
<div class="control-group">
  <%= f.label :salary_low, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :salary_low, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:salary_low]) %>
</div>
<div class="control-group">
  <%= f.label :salary_high, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :salary_high, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:salary_high]) %>
</div>
<div class="control-group">
  <%= f.label :successful?, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :successful?, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:successful?]) %>
</div>
<div class="control-group">
  <%= f.label :title, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:title]) %>
</div>
<div class="control-group">
  <%= f.label :work_from_home, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :work_from_home, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:work_from_home]) %>
</div>
<div class="control-group">
  <%= f.label :type, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :type, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:type]) %>
</div>
<div class="control-group">
  <%= f.label :tags, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :tags, :class => 'form-control' %>
  </div>
  <%= error_span(@offer[:tags]) %>
</div>
<%= f.submit nil, :class => 'btn btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
offers_path, :class => 'btn btn-default' %>
<% end %>

app/views/offers/edit.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offers/index.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= will_paginate @offers, renderer: BootstrapPagination::Rails %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:company_id) %></th>
      <th><%= model_class.human_attribute_name(:country_code) %></th>
      <th><%= model_class.human_attribute_name(:country_name) %></th>
      <th><%= model_class.human_attribute_name(:currency_code) %></th>
      <th><%= model_class.human_attribute_name(:expires_at) %></th>
      <th><%= model_class.human_attribute_name(:nice_to_have) %></th>
      <th><%= model_class.human_attribute_name(:perks) %></th>
      <th><%= model_class.human_attribute_name(:published_at) %></th>
      <th><%= model_class.human_attribute_name(:reward) %></th>
      <th><%= model_class.human_attribute_name(:remote) %></th>
      <th><%= model_class.human_attribute_name(:relocation_paid) %></th>
      <th><%= model_class.human_attribute_name(:role_description) %></th>
      <th><%= model_class.human_attribute_name(:salary_low) %></th>
      <th><%= model_class.human_attribute_name(:salary_high) %></th>
      <th><%= model_class.human_attribute_name(:successful?) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:work_from_home) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
    <tr>
      <td><%= offer.id%></td>
      <td><%= offer.city %></td>
      <td><%= offer.company_id %></td>
      <td><%= offer.country_code %></td>
      <td><%= offer.country_name %></td>
      <td><%= offer.currency_code %></td>
      <td><%= offer.expires_at %></td>
      <td><%= offer.nice_to_have %></td>
      <td><%= offer.perks %></td>
      <td><%= offer.published_at %></td>
      <td><%= offer.reward %></td>
      <td><%= offer.remote %></td>
      <td><%= offer.relocation_paid %></td>
      <td><%= offer.role_description %></td>
      <td><%= offer.salary_low %></td>
      <td><%= offer.salary_high %></td>
      <td><%= offer.successful? %></td>
      <td><%= offer.title %></td>
      <td><%= offer.work_from_home %></td>
      <td><%= offer.type %></td>
      <td><%= offer.tags %></td>
      <td><%=l offer.created_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offers/show.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @offer.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_id) %>:</strong></dt>
  <dd><%= @offer.company_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_code) %>:</strong></dt>
  <dd><%= @offer.country_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_name) %>:</strong></dt>
  <dd><%= @offer.country_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:currency_code) %>:</strong></dt>
  <dd><%= @offer.currency_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expires_at) %>:</strong></dt>
  <dd><%= @offer.expires_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nice_to_have) %>:</strong></dt>
  <dd><%= @offer.nice_to_have %></dd>
  <dt><strong><%= model_class.human_attribute_name(:perks) %>:</strong></dt>
  <dd><%= @offer.perks %></dd>
  <dt><strong><%= model_class.human_attribute_name(:published_at) %>:</strong></dt>
  <dd><%= @offer.published_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reward) %>:</strong></dt>
  <dd><%= @offer.reward %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remote) %>:</strong></dt>
  <dd><%= @offer.remote %></dd>
  <dt><strong><%= model_class.human_attribute_name(:relocation_paid) %>:</strong></dt>
  <dd><%= @offer.relocation_paid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role_description) %>:</strong></dt>
  <dd><%= @offer.role_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salary_low) %>:</strong></dt>
  <dd><%= @offer.salary_low %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salary_high) %>:</strong></dt>
  <dd><%= @offer.salary_high %></dd>
  <dt><strong><%= model_class.human_attribute_name(:successful?) %>:</strong></dt>
  <dd><%= @offer.successful? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @offer.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:work_from_home) %>:</strong></dt>
  <dd><%= @offer.work_from_home %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @offer.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @offer.tags %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
offers_path, :class => 'btn btn-default'  %>

app/views/search/search.html.erb
<div class="row main-row">
  <div class="search col-md-8 col-md-offset-2 center">
    <h1>What are you good at?</h1>
    <br>
    <div id="skills-search center">
      <%=  simple_form_for search_path, method: :get do |f| %>
      <div class="row">
        <%= f.collection_check_boxes "query", LANGUAGES, "to_s","to_s",  {:item_wrapper_class => 'btn btn-large btn-default btn-lg button-checkbox'} %>
      </div>
      <hr/>
      <div class = "row">
        <div class = "center">
          <%= f.collection_check_boxes "query", FRAMEWORKS, "to_s","to_s",{:item_wrapper_class => ' btn btn-large btn-default btn-lg button-checkbox'} %>
        </div>
      </div>
      <hr/>
      <div class = "row">
        <%= f.submit "Search", :class => "btn btn-large btn-default btn-lg search-button"  %>
      </div>
      <% end %>
    </div>
    <hr/>
     <small><em> There are currently <%= offers_count%> job offers amoung <%= companies_count%> Companies. </em></small>
  </div>
  <div class="results col-md-12" >
    <div class="row search-result main-row">
      <%= render 'companies/index', :options => {:companies => @companies}  %>
    </div>
  </div>
</div>
</div>